m = mean(x);
a = 20.769223273;
  s = log(m) - mean(log(x));
  as = linspace(0,a+5,100);
f = -(as-1).*s - gammaln(as) + as.*log(as) - as;
fa = -(a-1).*s - gammaln(a) + a.*log(a) - a;
as2 = linspace(0,a+5,100);
dfa = -s - digamma(a) +log(a);
d2fa = -trigamma(a) + (1/a);
kf = fa - (dfa.*dfa)/(2.*d2fa);
af = a - dfa/d2fa;
b = d2fa;
g = kf + (b/2)*af*af - (af*b).*as2 + (b/2).*as2.*as2;
plot(as, f, '-', as2, g, '-r');
hold on;
anewton = a + (digamma(a)+s-log(a))/(-trigamma(a)+(1/a))
ga = kf + (b/2)*af*af - (af*b)*anewton + (b/2)*anewton*anewton;
c2 = (-d2fa).*a.*a;
c1 = (dfa-(c2./a));
c0 = fa - c1*a-c2*log(a);
g2 = c0 + c1.*as+c2.*log(as);
 g = log(a)-s-digamma(a);
  h = 1/a - trigamma(a);
  a = 1/(1/a + g/(a^2*h));
g2a = c0 + c1.*a+c2.*log(a);
plot(as, g2, '-g');
legend('Objective Function', 'Newton''s Algorithm','Generalized Newton');
plot(anewton, ga, 'ro');
hold on;
plot(a, g2a, 'go');
xlabel('x');
ylabel('The log-likelihood of x');
hold off;
g2a = c0 + c1.*a+c2.*log(a);
print -depsc zeroGammaApproximation;